### ISSUE TITLE
Ponytail 4 

### ISSUE THREAD

**Issue by roer-MisterR** [RU-CMSS13/RU-CMSS13#101]
### Testmerges

#96: '#TESTMERGE Крупное обновление, ЕРТ карта и Алмайер, частичная русификация шагохода, несколько новых "привычных" для сс13 звуков, респрайт некоторых причесок.' by XDinka at commit d0391f728c

### Description of the bug

Самую классную причёску из SS13 убрали офы CM13, добавив свою каличную. Прошу изменить или добавить старую.

### What's the difference with what should have happened?

Причёска вернётся, будет классно и хорошо.

### How do we reproduce this bug?

Открыть меню персонажа. Открыть Hair and Eyes - ты выликолепен.

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by XDinka** [comment]
Прическа впилена, вроде как. Появится как решу траблы с юнит тестами и обновление будет готово к тест мержу
